## Basic ML Homework
### Модуль 4: Теоретический минимум для ML: линейная алгебра, начала мат.анализа

In [30]:
import numpy as np
import numpy.linalg as la
float_formatter = lambda x: "%.3f" % x
import matplotlib.pyplot as plt
import matplotlib as plt
import PIL
%matplotlib inline

## 1. Линейная алгебра

1.1 Даны матрицы $A = \begin{pmatrix}
2 & −4 \\
3 & 5 \\
−1 & 0 
\end{pmatrix},
$
$B = \begin{pmatrix}1 & 2 & 7 \\ −3 & −4 & 0 \\ 5 & 2 & 1 \end{pmatrix}$, $C = \begin{pmatrix}
6 & −3 & 9 \\
4 & −5 & 2 \\
8 & 1 & 5
\end{pmatrix}.$

Посчитайте матрицу $D = A^{\top}C - 2A^{\top}B^{\top}$. Приведите полную последовательность вычислений.

In [24]:
A = np.array([[2,-4], 
             [3,5],
             [-1,0]])
B = np.array([[1,2,7],
             [-3,-4,0],
             [5,2,1]])
C = np.array([[6,-3,9],
             [4,-5,2],
             [8,1,5]])
AT = np.transpose(A)
print(A)
print(AT)
X = AT.dot(C)
print(X)
BT = np.transpose(B)
print(B)
print(BT)
Y = 2 * AT.dot(BT)
print(Y)
D = X - Y
print(D)
# другой вариант: Z = np.transpose(A).dot(C) - 2 * np.transpose(A).dot(np.transpose(B))

[[ 2 -4]
 [ 3  5]
 [-1  0]]
[[ 2  3 -1]
 [-4  5  0]]
[[ 16 -22  19]
 [ -4 -13 -26]]
[[ 1  2  7]
 [-3 -4  0]
 [ 5  2  1]]
[[ 1 -3  5]
 [ 2 -4  2]
 [ 7  0  1]]
[[  2 -36  30]
 [ 12 -16 -20]]
[[ 14  14 -11]
 [-16   3  -6]]


1.2 Дано:

$ 3 \cdot \begin{pmatrix} x & 2 & 3 \\ −1 & y & 4 \end{pmatrix} +
2 \cdot \begin{pmatrix} 1 & 2 & −5 \\ 2 & −6 & z \end{pmatrix} =
\begin{pmatrix}
8 & v & −1 \\
1 & 6 & 4 \end{pmatrix}. $

Найдите значения $x$, $y$, $z$, и $v$.

In [25]:
A = np.array([['x',2,3], 
             [-1,'y',4]])
B = np.array([[1,2,-5],
             [2,-6,'z']])
C = np.array([[8,'v',-1],
             [1,6,4]])
# 3A + 2B = C

# 3 * A[0,0] + 2 * B[0,0] = C[0,0]
# A[0,0] = 6 / 3
# print(A[0,0])

# 3x + 2*1 = 8
x = 6 / 3
print(x)

# 3 * A[1,1] + 2 * B[1,1] = C[1,1]
# A[1,1] = 18 / 3

# 3y - 2*6 = 6
y = 18 / 3
print(y)

# 3 * A[1,2] + 2 * B[1,2] = C[1,2]
# B[1,2] = -8 / 2

# 3*4 + 2*z = 4
z = -8 / 2
print(z)

# 3 * A[0,1] + 2 * B[0,1] = C[0,1]
# C[0,1] = 6 + 4

# 3*2 + 2*2 = z
z = 6 + 4
print(z)

2.0
6.0
-4.0
10


1.3 На множестве $\mathbf{M}$ всех упорядоченных пар $(u; v)$ положительных чисел операции сложения и умножения введены
следующим образом:

$$
(u_1; v_1) + (u_2; v_2) = (u_1 \cdot u_2; v_1 \cdot v_2); 
λ(u; v) = (u^{\lambda}; v^{\lambda}),
$$

где $\lambda$ – вещественное число. Докажите, что при этом множество $\mathbf{M}$ становится линейным пространством. Выясните: а) какая пара играет роль нулевого элемента; б) какая пара является противоположной паре $(u; v)$; в) укажите размерность этого пространства и какой-нибудь его базис.

Положительные числа входят множество вещественных чисел. Множество М является линейным, т.к.:
1. x+y=y+x любое x,y принадлежит M:

(u1;v1)+(u2;v2)=(u1*u2;v1*v2)=(u2*u1;v2*v1)=(u2;v2)+(u1;v1)

2. (x+y)+z=x+(y+z) любое x,y,z принадлежит M:

((u1;v1)+(u2;v2))+(u3;v3)=(u1*u2;v1*v2)+(u3;v3)=(u1*u2*u3;v1*v2*v3)=(u1;v1)+(u2*u3;v2*v3)=(u1;v1)+((u2;v2)+(u3;v3))

3. Нулевой элемент x+0=x

(u1;v1)+(u2;v2)=(u1*u2;v1*v2)=(u1*1;v1*1) Нулевой элемент (1;1)

4. Пара, противоположная (u;v): -x+x=0

-(u;v)+(u;v)=0 Противоположная пара: -(u;v)=(-v;-u)

5. Размерность пространства и базис:
Возьмем единичные вектора пространства М:
е1 = (u1;v1) = (1,0)
e2 = (u2;v2) = (0,1)
Примем эти вектора в качестве строк матрицы, тогда размерность матрицы будет 2х2, а ранг матрицы будет 2.
Т.к. в матрице 2 вектора, то размерность пространства двух-мерных векторов М будет равна 2, а базисом этого пространства будут эти два единичных вектора: e1 c координатами (1,0) и вектор е2 с координатами (0,1).

1.4 Докажите, что множество всех квадратных матриц второго порядка с известными операциями сложения и умножения на число образуют четырехмерное линейное пространство. Укажите какой-нибудь базис этого пространства.

In [ ]:
Алгебраически четырехмерное пространство может быть построено как множество векторов с четырьмя вещественными координатами.
Пространство является линейным, если в этом множестве векторов введены операции сложения двух векторов
и умножения их на число. Вектор можно рассмотреть как матрицу с n строками и 1 столбцом. 

In [26]:
#сначала проверим на примере двух матриц сложение и умножение на число 
A = np.array([[1,2], 
             [3,4]])
B = np.array([[5,6],
             [7,8]])
D = A + B
C = B * 3
print(D)
print(C)

#конвертируем эти матрицы в вектора и проверим на примере полученных векторов сложение и умножение на число

Av = A.flatten()
#AV = np.array(Av)
print(Av)

Bv = B.flatten()
#BV = np.array(Bv)
print(Bv)

F = Av + Bv
G = Bv * 3
print(F)
print(G)

# базис
Basis = np.array([[1,0,0,0], 
                 [0,1,0,0], 
                 [0,0,1,0], 
                 [0,0,0,1]])

# Проверка по формуле: Вектор = Базис * Координаты вектора в этом базисе
# Т.к. взяли стандартный базис, то координаты вектора A в этом базисе должны быть такими же, как вектор А, 
# координаты вектора В должна быть такими же как вектор В
AvBas = Basis.dot(np.array([1,2,3,4]))
BvBas = Basis.dot(np.array([5,6,7,8]))
print(AvBas)
print(BvBas)

[[ 6  8]
 [10 12]]
[[15 18]
 [21 24]]
[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]
[15 18 21 24]
[1 2 3 4]
[5 6 7 8]


1.5 Укажите те значения параметров $p$ и $q$, при которых
ранг матрицы $A = \begin{pmatrix} 1 & 2 & 3 \\ 3 & 6 & p \\ 5 & 10 & q \end{pmatrix}$ равен единице.

In [27]:
# Ранг матрицы будет равен единице, если в матрице после элементарных преобразований останется одна строчка/один столбец.
A = np.array([[1,2,3], 
             [3,6,'p'],
             [5,10,'q']])
# Вычтем из второй строки первую, умноженную на 3. Получим матрицу:
A = ([[1,2,3], 
     [0,0,'p-9'],
     [5,10,'q']])
# Чтобы третий элемент второй строки стал равен нулю, нужно решить уравнение и найти значение p: p-9=0, значит p=9
# Вычтем из третьей строки первую, умноженную на 5. Получим матрицу:
A = ([[1,2,3], 
     [0,0,0],
     [0,0,'q-15']])
# Чтобы третий элемент третьей строки стал равен нулю, нужно решить уравнение и найти значение q: q-15=0, значит q=15
# Получим матрицу с рангом 1
A = ([[1,2,3], 
     [0,0,0],
     [0,0,0]])
A = ([1,2,3])

1.6 Относительно канонического базиса в $\mathbb{R}^2$ даны три вектора $f_1 = (2, −5)$, $f_2 = (−1, 3)$, $x = (1, −4)$. Докажите, что векторы $f_1$ и $f_2$ можно принять за новый базис, и найдите координаты вектора $x$ в этом базисе

In [28]:
# Если вектора линейно независимы, то они могут быть базисными векторами. 
# Для этого создадим матрицу из векторов f1 и f2, и найдем определитель нового базиса.
C = np.array([[2,-1], 
             [-5,3]])

detC = np.linalg.det(C)
print(detC) # Определитель матрицы отличен от нуля, значит вектора могут быть базисными.

#B - канонический базис 
B = np.array([[1,0], 
             [0,1]])
x = np.array([[1], 
             [-4]])

# Найдем координаты вектора х в новом базисе, предварительно найдем обратную матрицу для С
Сinv = np.linalg.inv(C)
D = Сinv.dot(B)
xcoord = D.dot(x)
print(xcoord)

1.0000000000000002
[[-1.]
 [-3.]]


1.7 Предположим, что существует линейный оператор, выраженный в базисе $(e_1, e_2)$ в виде матрицы $A = \begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}$. Найдите матрицу данного оператора в базисе из векторов $(\tilde{e}_1, \tilde{e}_2)$, если:

$$
\begin{cases}
\tilde{e}_1 = -2e_1 + 5e_2 \\
\tilde{e}_2 = -e_1 + 2e_2
\end{cases}.
$$

In [29]:
A = np.array([[1,0], 
             [0,2]])
# Найдем матрицу перехода от базиса (e1, e2) к новому базису
B = np.array([[-2,5],
             [-1,1]])
# Найдем обратную матрицу для B
Binv = np.linalg.inv(B)
print(Binv)
# Найдем матрицу линейного оператора в новом базисе
Anew = Binv.dot(A).dot(B)

print(Anew)

[[ 0.33333333 -1.66666667]
 [ 0.33333333 -0.66666667]]
[[ 2.66666667 -1.66666667]
 [ 0.66666667  0.33333333]]


## 2. Начала математического анализа

1. Найти матрицу Гессе следующей функции:
$$
    f(x,y) = x^3 - 2xy + y^2 - 3x - 2y.
$$

    Доп.задание (явно в курсе не обсуждалось): найдите точки локального экстремума функции $f$.

1.Найдем частные производные 


$\frac{\partial x,y}{\partial x}$ = 3x$^{2}$ - 2y - 3

$\frac{\partial x,y}{\partial y}$ = -2x + 2y - 2

 
2.Построим матрицу Гессе $H = \begin{pmatrix} 6x & -2 \\ -2 & 2 \end{pmatrix}$

3.Найдем точки локального экстремума функции.

Для удобства написания заменим f(x,y) на z

3а) Найдем стационарные точки M$_{0}$. 
Для этого возьмем частные производные:

z$_{x}^{'}$ = 3x$^{2}$ - 2y - 3

z$_{y}^{'}$ = -2x + 2y - 2

Контроль:

z$_{xy}^{"}$ = (3x$^{2}$ - 2y - 3)$_{y}^{'}$ = -2

z$_{yx}^{"}$ = (-2x + 2y - 2)$_{x}^{'}$ = -2

Чтобы найти экстремум должны выполняться условия z$_{x}^{'}$M($_{0}$) = 0 и z$_{y}^{'}$M($_{0}$) = 0

$$
\begin{cases}
\ z_{x}^{'} = 0 \\ 
\ z_{y}^{'} = 0
\end{cases}
$$

$$
\begin{cases}
\ 3x^{2} - 2y - 3 = 0 \\ 
\ -2x + 2y - 2 = 0 
\end{cases}
$$

Решим систему уравнений. Выразим y через x.

2y - 2x - 2 = 0

y = x + 1

Подставим у в первое уравнение, найдем x.

3x$^{2}$ - 2(x + 1) - 3 = 0

3x$^{2}$ - 2x -5 = 0

D = b$^{2}$ - 4ac = 4 - 4 * 3 * (-5) = 4 + 60 = 64

\begin{equation}
x_{1} = \frac{(-b+\sqrt{D})}{2a} = \frac{2+\sqrt{64}}{2 * 3} = \frac{10}{6} = 1\frac{2}{3}
\end{equation}

\begin{equation}
x_{2} = \frac{(-b-\sqrt{D})}{2a} = \frac{2-\sqrt{64}}{2 * 3} = \frac{-6}{6} = -1
\end{equation}

Теперь найдем значения у

\begin{equation}
y_{1} = 2\frac{2}{3}
\end{equation}

\begin{equation}
y_{2} = 0
\end{equation}

Таким образом нашли точки M$_{0}$

$$
M_{01}(1\frac{2}{3};2\frac{2}{3}), M_{02}(-1;0)
$$

Проверка:

z$_{x}^{'}(M_{01})$ = 3x$^{2}$ - 2y - 3 = 3 * (1$\frac{2}{3})^{2}$ - 2 * 2$\frac{2}{3}$ - 3 = 3 * $\frac{25}{9}$ - $\frac{16}{3}$ - 3 = $\frac{75}{9}$ - $\frac{16}{3}$ - 3 = $\frac{75}{9}$ - $\frac{48}{9}$ - $\frac{27}{9}$ = 0

z$_{y}^{'}(M_{01})$ = -2x + 2y - 2 = -2 * (1$\frac{2}{3})$ + 2 * 2$\frac{2}{3}$ - 2 = -2 * $\frac{5}{3}$ + 2 * $\frac{8}{3}$ - 2 = $\frac{-10}{3}$ + $\frac{16}{3}$ - $\frac{6}{3}$ = 0

z$_{x}^{'}(M_{02})$ = 3 * 1 - 2 * 0 - 3 = 0

z$_{y}^{'}(M_{02})$ = -2 * (-1) + 2 * 0 - 2 = 0


3b) Найдем частные производные второго порядка, чтобы выяснить какие это точки экстремума: минимум, максимум, перевал.

A = z$_{xx}^{"}(M_{0})$ = (3x$^{2}$ - 2y - 3)$_{x}^{'}$ = 6x

B = z$_{xy}^{"}(M_{0})$ = (3x$^{2}$ - 2y - 3)$_{x}^{'}$ = -2

C = z$_{yy}^{"}(M_{0})$ = (-2x + 2y - 2)$_{y}^{'}$ = 2

3с) Проверим выполнение достаточного условия экстремума для каждой точки М.


Для точки M$_{01}(1\frac{2}{3};2\frac{2}{3})$:

A = 6 * 1$\frac{2}{3}$ = 10

АС - B$^{2}$ = 10 * 2 - (-2)$^{2}$ = 20 - 4 = 16 > 0, значит функция z имеет экстремум в точке M$_{01}(1\frac{2}{3};2\frac{2}{3})$, т.к. А > 0, то это минимум. Найдем его:

z$_{min}$ = z(M$_{01}$) = z(1$\frac{2}{3};2\frac{2}{3}$) = x$^{3}$ - 2xy + y$^{2}$ - 3x - 2y = (1$\frac{2}{3}$)$^{3}$ - 2 * 1$\frac{2}{3}$ * 2$\frac{2}{3}$ + (2$\frac{2}{3}$)$^{2}$ - 3 * 1$\frac{2}{3}$)$ - 2 * 2\frac{2}{3}$ = -7$\frac{13}{27}$


Для точки M$_{02}(-1;0)$:

A = 6 * (-1) = -6

АС - B$^{2}$ = (-6) * 2 - (-2)$^{2}$ = -12 - 4 = -16 < 0, значит  в точке M$_{02}(-1;0)$ нет экстремума. 


Ответ: локальный минимум функции в точке M$_{01}(1\frac{2}{3};2\frac{2}{3})$ составляет -7$\frac{13}{27}$

2. Проверьте, что функция $f = \ln(\sqrt{x} + \sqrt{y})$ удовлетворяет уравнению:

$$
x \frac{\partial f}{\partial x} + y \frac{\partial f}{\partial y} = \frac{1}{2}.
$$

1.Найдем частные производные 


$\frac{\partial f}{\partial x}$ = 
(ln($\sqrt{x} + \sqrt{y})_{x}^{'}$ = 
$\frac{1}{\sqrt{x} + \sqrt{y}}$ ($\sqrt{x} + \sqrt{y})_{x}^{'}$ = 
$\frac{1}{\sqrt{x} + \sqrt{y}}$ $\frac{x^{'}}{2\sqrt{x}}$ = 
$\frac{1}{\sqrt{x} + \sqrt{y}}$ $\frac{1}{2\sqrt{x}}$  = 
$\frac{1}{(\sqrt{x} + \sqrt{y}) 2 \sqrt{x}}$ = 
$\frac{1}{2\sqrt{x} \sqrt{x} + 2 \sqrt{x} \sqrt{y}}$ = 
$\frac{1}{2x + 2 \sqrt{x} \sqrt{y}}$ = 
$\frac{1}{2} \frac{1}{x + \sqrt{x} \sqrt{y}}$


$\frac{\partial f}{\partial y}$ = 
(ln($\sqrt{x} + \sqrt{y})_{y}^{'}$ = 
$\frac{1}{\sqrt{x} + \sqrt{y}}$ ($\sqrt{x} + \sqrt{y})_{y}^{'}$ = 
$\frac{1}{\sqrt{x} + \sqrt{y}}$ $\frac{y^{'}}{2\sqrt{y}}$ = 
$\frac{1}{\sqrt{x} + \sqrt{y}}$ $\frac{1}{2\sqrt{y}}$  = 
$\frac{1}{(\sqrt{x} + \sqrt{y}) 2 \sqrt{y}}$ = 
$\frac{1}{2\sqrt{y} \sqrt{x} + 2 \sqrt{y} \sqrt{y}}$ = 
$\frac{1}{2y + 2 \sqrt{x} \sqrt{y}}$ = 
$\frac{1}{2} \frac{1}{y + \sqrt{x} \sqrt{y}}$


2.Подставим полученные производные в уравнение и решим его 

<br>

$
x  \frac{1}{2}  \frac{1}{x + \sqrt{x} \sqrt{y}} + y \frac{1}{2} \frac{1}{y + \sqrt{x} \sqrt{y}} = \frac{1}{2} \\
$
<br>
$
x \frac{1}{x + \sqrt{x} \sqrt{y}} + y \frac{1}{y + \sqrt{x} \sqrt{y}} = 1 \\
$
<br>
$
\frac{x (y + \sqrt{x} \sqrt{y}) + y (x + \sqrt{x} \sqrt{y})}{(x + \sqrt{x} \sqrt{y}) (y + \sqrt{x} \sqrt{y})} = 1 \\
$
<br>

Рассчитаем числитель

$x (y + \sqrt{x} \sqrt{y}) + y (x + \sqrt{x} \sqrt{y}) = \\
xy + x \sqrt{x} \sqrt{y} + xy +  y \sqrt{x} \sqrt{y} = \\
2xy + x \sqrt{x} \sqrt{y} + y \sqrt{x} \sqrt{y} = \\ 
2xy + \sqrt{x} \sqrt{y} (x + y) = \\
\sqrt{x} \sqrt{y} (2 \sqrt{x} \sqrt{y} + x + y) = \\
\sqrt{x} \sqrt{y} (\sqrt{x}  + \sqrt{y})^{2}
$

<br>

Рассчитаем знаменатель

$(x + \sqrt{x} \sqrt{y}) (y + \sqrt{x} \sqrt{y}) = \\
xy + x \sqrt{x} \sqrt{y} + y \sqrt{x} \sqrt{y} + xy = \\
2xy + x \sqrt{x} \sqrt{y} + y \sqrt{x} \sqrt{y} = \\
\sqrt{x} \sqrt{y} (2 \sqrt{x} \sqrt{y} + x + y) = \\
\sqrt{x} \sqrt{y} (\sqrt{x}  + \sqrt{y})^{2}
$

<br>

Подставим полученные числитель и знаменатель в уравнение

$
\frac{\sqrt{x} \sqrt{y} (\sqrt{x}  + \sqrt{y})^{2}}{\sqrt{x} \sqrt{y} (\sqrt{x}  + \sqrt{y})^{2}} = 1 \\
$


Таким образом доказали, что функция удовлетворяет уравнению.

3. Используя правило для вычисления производной сложной функции, найдите полный дифференциал $\frac{df}{dt}$, если $$f = e^{xy}\ln(x+y), \quad x = 2t^2, \quad y = 1 - 2t^2 .$$

1.Запишем формулу для поиска полного дифференциала

$\frac{df}{dt}$ = 
$\frac{\partial f}{\partial x} \frac{dx}{dt} + \frac{\partial f}{\partial y} \frac{dy}{dt}$

<br>

2.Найдем каждый компонент этой формулы
<br>
$
\frac{\partial f}{\partial x} = (e^{xy} ln(x + y))_{x}^{'} = \\
(e^{xy})_{x}^{'} ln(x + y) + e^{xy} (ln(x + y))_{x}^{'} = \\
e^{xy}(xy)_{x}^{'}ln(x + y) + e^{xy}\frac{(x+y)_{x}^{'}}{x+y} = \\
e^{xy}y ln(x+y) + e^{xy}\frac{1}{x+y} = \\
e^{xy}(y ln(x+y) + \frac{1}{x+y})
$
<br>

$
\frac{\partial f}{\partial y} = (e^{xy} ln(x + y))_{y}^{'} = \\
(e^{xy})_{y}^{'} ln(x + y) + e^{xy} (ln(x + y))_{y}^{'} = \\
e^{xy}(xy)_{y}^{'}ln(x + y) + e^{xy}\frac{(x+y)_{y}^{'}}{x+y} = \\
e^{xy}x ln(x+y) + e^{xy}\frac{1}{x+y} = \\
e^{xy}(x ln(x+y) + \frac{1}{x+y})
$
<br>

$
\frac{dx}{dt} = (2t^{2})^{'} = 4t
$
<br>

$
\frac{dy}{dt} = (1 - 2t^{2})^{'} = 0 - 4t = -4t
$
<br>
<br>
3.Подставим найденные компоненты в основную формулу и найдем полный дифференциал
<br>
<br>
$
\frac{df}{dt} = e^{xy}(y ln(x+y) + \frac{1}{x+y})4t + e^{xy}(x ln(x+y) + \frac{1}{x+y})(-4t) = \\
4te^{xy}(y ln(x+y) + \frac{1}{x+y}) - 4te^{xy}(x ln(x+y) + \frac{1}{x+y}) = \\
4te^{xy}yln(x+y) + 4te^{xy}\frac{1}{x+y} - 4te^{xy}x ln(x+y) - 4te^{xy}\frac{1}{x+y} = \\
4te^{xy}yln(x+y) - 4te^{xy}xln(x+y) = \\
y4te^{xy}ln(x+y) - x4te^{xy}ln(x+y) = \\
(y-x)4te^{xy}ln(x+y) = \\
4te^{xy}ln(x+y)(y-x)
$

Таким образом полный дифференциал функции будет
$
\frac{df}{dt} = 4te^{xy}ln(x+y)(y-x)
$

4. Предположим, задана функция $f: \mathbb{R}^3 \rightarrow \mathbb{R}^2$

$$
    f(x,y,z) = (x+y+z, xyz).
$$

   Найдите матрицу Якоби функции $f$, и её численное значение в точке $v = (1, 2, 3)$.

Чтобы составить матрицу Якоби нужно найти частные производные функции $x+y+z$ и функции $xyz$

Матрица Якоби:

$
J = \begin{pmatrix} 
\frac{\partial (x+y+z)}{\partial x} & \frac{\partial (x+y+z)}{\partial y} & \frac{\partial (x+y+z)}{\partial z} \\
\frac{\partial xyz}{\partial x} & \frac{\partial xyz}{\partial y} & \frac{\partial xyz}{\partial z}
\end{pmatrix} = 
\begin{pmatrix} 1 & 1 & 1 \\ yz & xz & xy \end{pmatrix}
$

<br>
Значение в точке v = (1, 2, 3):
$
J = \begin{pmatrix} 1 & 1 & 1 \\ 6 & 3 & 2 \end{pmatrix}
$